name: Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # yarnのキャッシュ
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-icon-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-icon

      - name: Install
        run: yarn --frozen-lockfile

      - name: Prettier
        run: yarn format check-changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: yarn lint:ci

      - name: Generate story
        run: yarn build:manifest

      - name: '`yarn build:manifest` changes committed?'
        run: git diff --exit-code

      - name: Snapshot Test
        run: yarn test:snapshot

      - name: Build
        run: yarn build
